# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/formalyzer',
                'doc_host': 'https://drscotthawley.github.io',
                'git_url': 'https://github.com/drscotthawley/formalyzer',
                'lib_path': 'formalyzer'},
  'syms': { 'formalyzer.core': { 'formalyzer.core.main': ('core.html#main', 'formalyzer/core.py'),
                                 'formalyzer.core.read_pdf_text': ('core.html#read_pdf_text', 'formalyzer/core.py'),
                                 'formalyzer.core.read_urls_file': ('core.html#read_urls_file', 'formalyzer/core.py')}}}
