# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/formalyzer',
                'doc_host': 'https://drscotthawley.github.io',
                'git_url': 'https://github.com/drscotthawley/formalyzer',
                'lib_path': 'formalyzer'},
  'syms': {'formalyzer.core': {'formalyzer.core.foo': ('core.html#foo', 'formalyzer/core.py')}}}
