# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['read_urls_file', 'read_pdf_text', 'main']

# %% ../nbs/00_core.ipynb 4
import os 

def read_urls_file(urls_file:str) -> list:
    "read a text file where each line is a url of a submission site" 
    with open(os.path.expanduser(urls_file)) as f:
        return f.read().splitlines()

# %% ../nbs/00_core.ipynb 6
from pypdf import PdfReader
import logging
logging.getLogger("pypdf").setLevel(logging.ERROR)

def read_pdf_text(pdf_file):
    reader = PdfReader(os.path.expanduser(pdf_file))
    return "\n".join(page.extract_text() for page in reader.pages)

# %% ../nbs/00_core.ipynb 12
import os 
from fastcore.script import call_parse

@call_parse
def main(pdf_path: str, urls: str, debug: bool = False):
    pdf_path = os.path.expanduser(pdf_path) 
    assert os.path.exists(pdf_path), f"File not found: {pdf_path}"
    if os.path.exists(os.path.expanduser(urls)): 
        if debug: print(f"File {urls} exists. Reading.")
        urls = read_urls_file(urls)
    else: 
        print(f"No file {urls}. Treating it as a single url") 
        urls = [urls] 
    if debug: print("urls =\n",urls)
    letter_text = read_pdf_text(pdf_path)
    if debug: print("letter_text =\n",letter_text) 
